name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_PATH: /home/osi/youtubesplitterapp
      APP_NAME: youtubesplitterapp
      SSH_USERNAME: osi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            if [ ! -d ${{ env.APP_PATH }} ]; then
              git clone ${{ github.repository }} ${{ env.APP_PATH }}
            else
              cd ${{ env.APP_PATH }}
              git pull origin main --force
            fi

            cd ${{ env.APP_PATH }}
            python3 -m venv .venv
            source ${{ env.APP_PATH }}/.venv/bin/activate
            pip install -r requirements.txt

            echo "export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > ${{ env.APP_PATH }}/.env
            echo "export VIDEO_CHANNEL_ID=${{ secrets.VIDEO_CHANNEL_ID }}" >> ${{ env.APP_PATH }}/.env
            source ~/.bashrc

      - name: Restart App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            pm2 restart ${{ env.APP_NAME }}
